version: "3.9"
services:
  server-service:
    image: kelimetris-server:latest
    container_name: server-container
    ports:
      - "8080:8080"
    depends_on:
      - prod_db

  monitoring-service:
    image: kelimetris-monitoring:latest
    container_name: monitoring-container
    ports:
      - "8090:8090"
    depends_on:
      - prod_db
      - server-service

  prod_db:
    image: postgres:latest
    container_name: kelimetris_prod_db
    restart: always
    volumes:
      - prod_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: k3l1m3tr1s_adm
      POSTGRES_PASSWORD: k3l1m3tr1s_p4ss
      POSTGRES_DB: prod
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  prod_db:
    external: false
